generator:
  class:                          sfDoctrineGenerator
  param:
    model_class:                  sfGuardGroup
    theme:                        mooDoo.2
    non_verbose_templates:        true
    with_show:                    false
    singular:                     ~
    plural:                       ~
    route_prefix:                 sf_guard_group
    with_doctrine_route:          true
    actions_base_class:           sfActions

    config:
      actions: ~
      fields:  ~

      list:
        display:                  [ name, description ]

      filter:  ~
      form:    ~
      edit:    ~
      new:     ~