generator:
  class:                          sfDoctrineGenerator
  param:
    model_class:                  Formu
    theme:                        mooDoo.2
    non_verbose_templates:        true
    with_show:                    false
    singular:                     ~
    plural:                       ~
    route_prefix:                 formu
    with_doctrine_route:          true
    actions_base_class:           sfActions

    config:
      actions: ~
      fields:  ~

      list:
        #title:                    { label: Form }

      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
