generator:
  class:                          sfDoctrineGenerator
  param:
    model_class:                  RevisionState
    theme:                        mooDoo.2
    non_verbose_templates:        true
    with_show:                    false
    singular:                     ~
    plural:                       ~
    route_prefix:                 revision_state
    with_doctrine_route:          true
    actions_base_class:           sfActions

    config:
      actions: ~
      fields:  ~
      list:    ~
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
